"""some interesting change in the post model

Revision ID: 9397e17672e3
Revises: 564971fb394a
Create Date: 2020-02-24 14:47:56.312979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9397e17672e3'
down_revision = '564971fb394a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content_paragraph1', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('content_paragraph2', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('content_paragraph3', sa.Text(), nullable=True))
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('post', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', mysql.TEXT(), nullable=True))
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('post', 'content_paragraph3')
    op.drop_column('post', 'content_paragraph2')
    op.drop_column('post', 'content_paragraph1')
    # ### end Alembic commands ###
